var DEPARTEMENTS = [
  { code: "001", nom: "Ain" },
  { code: "002", nom: "Aisne" },
  { code: "003", nom: "Allier" },
  { code: "004", nom: "Alpes-de-Haute-Provence" },
  { code: "005", nom: "Hautes-Alpes" },
  { code: "006", nom: "Alpes-Maritimes" },
  { code: "007", nom: "Ardèche" },
  { code: "008", nom: "Ardennes" },
  { code: "009", nom: "Ariège" },
  { code: "010", nom: "Aube" },
  { code: "011", nom: "Aude" },
  { code: "012", nom: "Aveyron" },
  { code: "013", nom: "Bouches-du-Rhône" },
  { code: "014", nom: "Calvados" },
  { code: "015", nom: "Cantal" },
  { code: "016", nom: "Charente" },
  { code: "017", nom: "Charente-Maritime" },
  { code: "018", nom: "Cher" },
  { code: "019", nom: "Corrèze" },
  { code: "02A", nom: "Corse-du-Sud" },
  { code: "02B", nom: "Haute-Corse" },
  { code: "021", nom: "Côte-d'Or" },
  { code: "022", nom: "Côtes-d'Armor" },
  { code: "023", nom: "Creuse" },
  { code: "024", nom: "Dordogne" },
  { code: "025", nom: "Doubs" },
  { code: "026", nom: "Drôme" },
  { code: "027", nom: "Eure" },
  { code: "028", nom: "Eure-et-Loir" },
  { code: "029", nom: "Finistère" },
  { code: "030", nom: "Gard" },
  { code: "031", nom: "Haute-Garonne" },
  { code: "032", nom: "Gers" },
  { code: "033", nom: "Gironde" },
  { code: "034", nom: "Hérault" },
  { code: "035", nom: "Ille-et-Vilaine" },
  { code: "036", nom: "Indre" },
  { code: "037", nom: "Indre-et-Loire" },
  { code: "038", nom: "Isère" },
  { code: "039", nom: "Jura" },
  { code: "040", nom: "Landes" },
  { code: "041", nom: "Loir-et-Cher" },
  { code: "042", nom: "Loire" },
  { code: "043", nom: "Haute-Loire" },
  { code: "044", nom: "Loire-Atlantique" },
  { code: "045", nom: "Loiret" },
  { code: "046", nom: "Lot" },
  { code: "047", nom: "Lot-et-Garonne" },
  { code: "048", nom: "Lozère" },
  { code: "049", nom: "Maine-et-Loire" },
  { code: "050", nom: "Manche" },
  { code: "051", nom: "Marne" },
  { code: "052", nom: "Haute-Marne" },
  { code: "053", nom: "Mayenne" },
  { code: "054", nom: "Meurthe-et-Moselle" },
  { code: "055", nom: "Meuse" },
  { code: "056", nom: "Morbihan" },
  { code: "057", nom: "Moselle" },
  { code: "058", nom: "Nièvre" },
  { code: "059", nom: "Nord" },
  { code: "060", nom: "Oise" },
  { code: "061", nom: "Orne" },
  { code: "062", nom: "Pas-de-Calais" },
  { code: "063", nom: "Puy-de-Dôme" },
  { code: "064", nom: "Pyrénées-Atlantiques" },
  { code: "065", nom: "Hautes-Pyrénées" },
  { code: "066", nom: "Pyrénées-Orientales" },
  { code: "067", nom: "Bas-Rhin" },
  { code: "068", nom: "Haut-Rhin" },
  { code: "069", nom: "Rhône" },
  { code: "070", nom: "Haute-Saône" },
  { code: "071", nom: "Saône-et-Loire" },
  { code: "072", nom: "Sarthe" },
  { code: "073", nom: "Savoie" },
  { code: "074", nom: "Haute-Savoie" },
  { code: "075", nom: "Paris" },
  { code: "076", nom: "Seine-Maritime" },
  { code: "077", nom: "Seine-et-Marne" },
  { code: "078", nom: "Yvelines" },
  { code: "079", nom: "Deux-Sèvres" },
  { code: "080", nom: "Somme" },
  { code: "081", nom: "Tarn" },
  { code: "082", nom: "Tarn-et-Garonne" },
  { code: "083", nom: "Var" },
  { code: "084", nom: "Vaucluse" },
  { code: "085", nom: "Vendée" },
  { code: "086", nom: "Vienne" },
  { code: "087", nom: "Haute-Vienne" },
  { code: "088", nom: "Vosges" },
  { code: "089", nom: "Yonne" },
  { code: "090", nom: "Territoire de Belfort" },
  { code: "091", nom: "Essonne" },
  { code: "092", nom: "Hauts-de-Seine" },
  { code: "093", nom: "Seine-Saint-Denis" },
  { code: "094", nom: "Val-de-Marne" },
  { code: "095", nom: "Val-d'Oise" },
  { code: "971", nom: "Guadeloupe" },
  { code: "972", nom: "Martinique" },
  { code: "973", nom: "Guyane" },
  { code: "974", nom: "La Réunion" },
  { code: "976", nom: "Mayotte" },
];

// Remplir le sélecteur au chargement
(function() {
  var sel = document.getElementById("dept-select");
  var params = new URLSearchParams(window.location.search);
  var current = params.get("dept") || "044";
  DEPARTEMENTS.forEach(function(d) {
    var opt = document.createElement("option");
    opt.value = d.code;
    opt.textContent = d.code + " — " + d.nom;
    if (d.code === current) opt.selected = true;
    sel.appendChild(opt);
  });

  sel.addEventListener("change", function() {
    var params = new URLSearchParams(window.location.search);
    params.set("dept", sel.value);
    window.location.search = params.toString();
  });
})();